ASoC: codecs: tas2559: Add initial tas2559 audio amplifier codec
Introduce the TAS2559 audio codec.

Squash History:
tas2559: comment out load calibration function in order to build it as module
tas2559: fix symmetric_rates compilation error
tas2559: merge the files
tas2559: remove functions from header
tas2559: reorder, remove functions and structs from header. None of the other codecs have them in headers. sooooo.
ASoC: codecs: tas2559: cleanup
tas2559: irq cleanup complete
tas2559: compile fixes
tas2559: remove timer and temperature check
tas2559: remove calibiration related stuffs
tas2559: remove unncessary kcontrols
tas2559: remove yram checksum
tas2559: its fine, remove vboost control
tas2559: use gpiod and specifiy legacy_dai_naming

ASoC: codecs: tas2559: Fix build

Fixes:

    ../sound/soc/codecs/tas2559.c: In function 'tas2559_hw_reset':
    ../sound/soc/codecs/tas2559.c:496:9: error: implicit declaration of function 'gpiod_set_value_cansleep' [-Werror=implicit-function-declaration]
      496 |         gpiod_set_value_cansleep(pTAS2559->mnDevAGPIORST, 0);
          |         ^~~~~~~~~~~~~~~~~~~~~~~~
    ../sound/soc/codecs/tas2559.c: In function 'tas2559_parse_dt':
    ../sound/soc/codecs/tas2559.c:1866:35: error: implicit declaration of function 'devm_gpiod_get'; did you mean 'em_pd_get'? [-Werror=implicit-function-declaration]
     1866 |         pTAS2559->mnDevAGPIORST = devm_gpiod_get(dev, "ti,tas2559-reset", GPIOD_OUT_LOW);
          |                                   ^~~~~~~~~~~~~~
          |                                   em_pd_get
    ../sound/soc/codecs/tas2559.c:1866:75: error: 'GPIOD_OUT_LOW' undeclared (first use in this function)
     1866 |         pTAS2559->mnDevAGPIORST = devm_gpiod_get(dev, "ti,tas2559-reset", GPIOD_OUT_LOW);
          |                                                                           ^~~~~~~~~~~~~
    ../sound/soc/codecs/tas2559.c:1866:75: note: each undeclared identifier is reported only once for each function it appears in
    cc1: some warnings being treated as errors
    make[4]: *** [../scripts/Makefile.build:252: sound/soc/codecs/tas2559.o] Error 1
    make[3]: *** [../scripts/Makefile.build:494: sound/soc/codecs] Error 2
    make[3]: *** Waiting for unfinished jobs....